# serverless.yml

service: beverlyhills-backend

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: server.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
